### PR TITLE
Updated Microsoft.CodeAnalysis.*.Workspace packages versions

### PR DESCRIPTION
**Pull request by cezarypiatek**
Hi

I've updated mentioned packages version to support the newest one.
Could you release updated nuget package?

### CODE REVIEW

**Comment by phoenix172** [comment]
The reason I used older versions of the packages, is because I found through expirementation that some visual studio versions don't support the newer ones. I wonder whether I should simply upload the new version and let people use the old one as needed.

**Comment by cezarypiatek** [comment]
Sounds reasonable for me. Currently it's not possible to install this nuget package to project that reference newer version of aforementioned libraries.

**Comment by phoenix172** [comment]
On a second thought, there is a problem. If any changes are introduced to the testing library they will only be available in the newest version, that uses the latest packages. I will see if I can get it to work with both newer and older packages using some Nuget magic a bit later.

**Comment by cezarypiatek** [comment]
It would be great. I need to write UI for code refactoring providers in my project https://github.com/cezarypiatek/MappingGenerator and this library will help me with that.

**Comment by phoenix172** [comment]
Wow, I just checked out your library and I must say it looks really awesome and is much simpler than automapper(because you see all the code that executes). I think I might have a use for it in a project of mine.

**Comment by phoenix172** [comment]
Ok I just played around with it a bit. RoslynNUnitLight references CSharp.Workspaces and VisualBasic.Workspaces 2.4.0, but references them in a way that lets you use a newer version as well, so there should not be a problem. If all you care about is the solution, skip to the last paragraph.

1. When I tried to add a reference to RoslynNUnitLight from a project using version 2.8.2 of one or both of those packages I got an error telling me the project needs to target .netstandard 2 and not .netstandard 1.3. Stating the obvious, I know, but still, you need to be targetting .netstandard 2

2. After I changed the project to target .netstandard 2, I got another error while trying to add the package:
image
Main project referencing CSharp.Workspaces 2.8.2 when RoslyNUnitLight requires 2.4.0, is fine. The problem is that RoslynNUnitLight also references VisualBasic.Workspaces. Since VisualBasic.Workspaces is not referenced in the main project, it adds it as a dependency of RoslynNUnitLight and the version that it selects is the one listed in the csproj of RoslynNUnitLight - 2.4.0.

So you have this:
MainProject -> CSharp.Workspaces 2.8.2 -> Workspaces.Common 2.8.2
MainProject -> NUnitLight.NetStandard 1.2.3 -> VisualBasic.Workspaces 2.4.0 -> Workspaces.Common 2.4.0

Meaning you are trying to add two different versions of the Workspaces.Common package - 2.8.2 and 2.4.0

The solution is to simply reference VisualBasic.Workspaces 2.8.2 from your main project. That way you will indirectly reference only Workspaces.Common 2.8.2, instead of both 2.8.2 and 2.4.0 and the project will build.

If you have a better idea on how to avoid having to reference VisualBasic.Workspaces from the main project, please do share.

**Comment by phoenix172** [comment]
Please tell me if the provided solution works for you so I can close the pull request.

**Comment by cezarypiatek** [comment]
I'm not convinced to this solution because this some kind of hack. If the library is provided as nuget package then the only correct way is to reference it as nuget package. Maybe the version requirement should be change using some kind of wildcard https://docs.microsoft.com/en-US/nuget/reference/package-versioning#version-ranges-and-wildcards

**Comment by phoenix172** [comment]
I understand your reasoning for calling it a hack. 

The Nuget package already uses a version range and not a specific required version. All it says is it requires a minimum version of 2.4.0. Problem is in the Roslyn CSharp and Visual Basic packages. They require an exact version of the Roslyn Common package.

CSharp and VisualBasic.Workspaces 2.4.0 require Common.Workspaces 2.4.0
CSharp and VisualBasic.Workspaces 2.8.2 require Common.Workspaces 2.8.2

You have only referenced CSharp.Workspaces 2.8.2 in your project, but RoslynNUnitLight also references VisualBasic.Workspaces and it defaults to version 2.4.0 for that. As a consequence you are trying to reference two different versions of the Common.Workspaces package and Nuget won't let you do that.
That is why you need to explicitly specify the version of the VisualBasic.Workspaces package by adding a reference in your project for version 2.8.2. 

All you have to do is add another package to the project with the correct version.

Please understand that there really isn't any other clean way to deal with the issue from my side, unless I make the library compatible with only the latest version of Roslyn.

**Comment by cezarypiatek** [comment]
Ok, I check your solution and I will let you know if it works. You should definitely add this information to Readme or Wiki.

**Comment by phoenix172** [comment]
Please do. Let me know if it works for you. An addition to readme sounds like a good idea.

**Comment by cezarypiatek** [comment]
You were right. Installing nuget package `Microsoft.CodeAnalysis.VisualBasic.Workspaces` 2.8.2 solved the problem. Thanks for your help.

**Comment by phoenix172** [comment]
Glad to help :) I will close the pull request.

**Pull request closed without merging**
